version: "3.8"

services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    volumes:
      - config:/config
      - data:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.michaelbick.duckdns.org`)"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
    restart: unless-stopped


networks:
  traefik:
    external: true
    name: traefik


volumes:
  config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/syncthing-config

  data:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=192.168.11.111,rw'
      device: ':/mnt/store/syncthing'
