- hosts: jails
  roles:
    - { role: secure_ssh, become: yes }

- hosts: sanoid
  become: yes
  tasks:
    - name: Install sanoid dependencies
      pkgng:
        name: 
          - p5-Config-IniFiles
          - p5-Capture-Tiny
          - pv
          - mbuffer
          - lzop
        state: present
