- hosts: sanoid
  become: yes
  tasks:
    - name: Install sanoid dependencies
      become: yes
      package:
        name: 
          - p5-Config-Inifiles
          - p5-Capture-Tiny
          - pv
          - mbuffer
          - lzop
        state: present
