- hosts: all
  tasks:
    - name: Update Apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: vm
  tasks:
    - name: Wait for automatic system updates
      become: yes
      shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
      loop:
        - lock
        - lock-frontend

- hosts: docker_host
  vars:
    docker_daemon_json_options:
      hosts:
        - tcp://0.0.0.0:2375
        - unix:///var/run/docker.sock

  roles:
    - { role: docker_override_systemd, become: yes }
    # - { role: geerlingguy.docker, become: yes }
    # This is a hotfix
    # until geerlinguy.docker implements the daemon options
    - { role: docker, become: yes}

- hosts: docker01
  pre_tasks:
    - name: Install storage packages needed for volume mounts
      become: yes
      package:
        name:
          - nfs-common
          - open-iscsi
        state: present

  roles:
    - role: iscsi_mount
      become: yes
      iscsi_portal: 192.168.11.111
      iscsi_target: iqn.2005-10.org.freenas.ctl:docker01-volumes
      iscsi_mountpoint: /mnt/docker_volumes
      iscsi_filesystem: ext4
    - role: docker_local_persist
      become: yes
      docker_local_persist_version: 1.3.0

- hosts: k3s_node
  roles:
    - xanmanning.k3s
