- hosts: vm
  tasks:
    - name: Wait for automatic system updates
      become: yes
      shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
      loop:
        - lock
        - lock-frontend

- hosts: all
  tasks:
    - name: Update Apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: docker_host
  vars:
    docker_daemon_json_options:
      hosts:
        - tcp://0.0.0.0:2375
        - unix:///var/run/docker.sock
  roles:
    - { role: docker-override-systemd, become: yes }
    # - { role: geerlingguy.docker, become: yes }
    # This is a hotfix
    # until geerlinguy.docker implements the daemon options
    - { role: docker, become: yes}
  tasks:
    - name: Install open-iscsi
      become: yes
      package:
        name:
          - open-iscsi
        state: present

    - name: Perform ISCSI discovery and show available target nodes
      become: yes
      open_iscsi:
        discover: yes
        portal: 192.168.11.111

    - name: Connect to the named target, after updating the local persistent database (cache)
      become: yes
      open_iscsi:
        auto_node_startup: yes
        login: yes
        target: iqn.2005-10.org.freenas.ctl:docker01-volumes

    - name: Create a new primary partition on the ISCSI target
      become: yes
      parted:
        device: /dev/sdb
        number: 1
        state: present

    - name: Create the ISCSI target filesystem
      become: yes
      filesystem:
        fstype: ext4
        dev: /dev/sdb1
        force: no

    - name: Create device mountpoint
      file:
        path: /mnt/docker_volumes
        state: directory

    - name: Mount device
      become: yes
      mount:
        path: /mnt/docker_volumes
        src: /dev/sdb1
        fstype: ext4
        state: present

- hosts: k3s_node
  roles:
    - xanmanning.k3s
