- hosts: vm
  roles:
    - { role: wait_for_lock, become: yes }

- hosts: all
  tasks:
    - name: Update Apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: vm
  roles:
    - { role: wait_for_lock, become: yes }

- hosts: docker01
  roles:
    - role: iscsi_mount
      become: yes
      iscsi_portal: 192.168.11.111
      iscsi_target: iqn.2005-10.org.freenas.ctl:docker01-volumes
      iscsi_mountpoint: /mnt/docker_volumes
      iscsi_filesystem: ext4
    - role: docker_local_persist
      become: yes
      docker_local_persist_version: 1.3.0

- hosts: k3s_node
  roles:
    - xanmanning.k3s
