- hosts: vm
  tasks:
    - name: Wait for automatic system updates
      become: yes
      shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
      loop:
        - lock
        - lock-frontend

- hosts: all
  tasks:
    - name: Update Apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: docker_host
  vars:
    docker_daemon_json_options:
      hosts:
        - tcp://0.0.0.0:2375
        - unix:///var/run/docker.sock
  roles:
    - { role: docker-override-systemd, become: yes }
    # - { role: geerlingguy.docker, become: yes }
    # This is a hotfix
    # until geerlinguy.docker implements the daemon options
    - { role: docker, become: yes}

- hosts: k3s_node
  roles:
    - xanmanning.k3s
