version: '3.7'
# volumes:
#   media:
#     driver: sapk/plugin-rclone:latest
#     driver_opts:
#       config: "$(base64 /vagrant/config/rclone/.rclone.conf)"
#       args: "--read-only --fast-list"
#       remote: "gt-onedrive:/media"

services:
  downloads-rclone:
    build:
      context: ./rclone-mount-wrapper
      target: ${BUILD_TYPE}
    # env_file:
    #   - .env
    # restart: on-failure
    environment:
      - RCLONE_REMOTE_MOUNT=${REMOTE_DIR}/downloads
      - PUID=10000
      - PGID=10000
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${LOCAL_DIR}/downloads:/data:shared
      # - ./config/rclone:/config:rw
    # command: ls -l /config

  # downloads-rclone:
  #   build:
  #     context: ./rclone-mount
  #     target: ${BUILD_TYPE}
  #   env_file:
  #     - .env
  #   # restart: on-failure
  #   environment:
  #     - RCLONE_REMOTE_MOUNT=${REMOTE_DIR}/downloads
  #     - PUID=10200
  #     - PGID=10200
  #   cap_add:
  #     - SYS_ADMIN
  #   devices:
  #     - /dev/fuse
  #   security_opt:
  #     - apparmor:unconfined
  #   volumes:
  #     - ${LOCAL_DIR}/downloads:/data:shared
  #     # - ./config/rclone:/config:rw
  #   # command: ls -l /config

  # torrent:
  #   build:
  #     context: ./torrent
  #   depends_on:
  #     - downloads-rclone
  #   volumes:
  #     - ${LOCAL_DIR}/downloads:/mnt/downloads:shared
  #   command: ls -l /mnt/downloads
