version: '3.7'
# volumes:
#   media:
#     driver: sapk/plugin-rclone:latest
#     driver_opts:
#       config: "$(base64 /vagrant/config/rclone/.rclone.conf)"
#       args: "--read-only --fast-list"
#       remote: "gt-onedrive:/media"

services:
  rclone-downloads:
    build:
      context: ./rclone-mount-wrapper
      target: ${BUILD_TYPE}
    # env_file:
    #   - .env
    # restart: on-failure
    environment:
      - RCLONE_REMOTE_MOUNT=${REMOTE_DIR}/downloads
      - PUID=${MEDIA_ID}
      - PGID=${MEDIA_ID}
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${LOCAL_DIR}/downloads:/data:shared

  transmission:
    image: linuxserver/transmission:145
    depends_on:
      - downloads-rclone
    volumes:
      - ${LOCAL_DIR}/downloads:/mnt/downloads:shared
    command: ls -l /mnt/downloads
