version: "3.8"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    networks:
      - trafeik
    ports:
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8090:8080
    volumes:
      # For Traefik's automated config to work, the docker socket needs to be
      # mounted. There are some security implications to this.
      # See https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
      # and https://docs.traefik.io/providers/docker/#docker-api-access
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:v5.0
    networks:
      macvlan:
        ipv4_address: 192.168.11.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: America/Los_Angeles
      WEBPASSWORD: 'this-is-a-Password!'
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    # Volumes store your data between container upgrades
    volumes:
       - pihole-config:/etc/pihole/
       - pihole-dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1 # Required to resolve dhcp hostnames from Pi-hole's DNSMasq
      # - 1.1.1.1 # Optional backup if DNSMasq has problems starting
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - sonarr-config:/config
      - media-center:/data
    networks:
      - internal
      - external
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - radarr-config:/config
      - media-center:/data
    networks:
      - internal
      - external
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true
      # - RUN_OPTS=run options here #optional
    volumes:
      - jackett-config:/config
      # - downloads:/downloads
    networks:
      - internal
      - external
    ports:
      - 9117:9117
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config
      - torrents:/downloads
    networks:
      - internal
      - external
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  plex:
    container_name: plex
    image: plexinc/pms-docker
    networks:
      macvlan:
        ipv4_address: 192.168.11.200
    environment:
      TZ: America/Los_Angeles
      PLEX_UID: 1000
      PLEX_GID: 1000
    volumes:
       - plex-config:/config
       - plex-transcode:/transcode
       - media:/data
    restart: unless-stopped


networks:
  trafeik:
    # external: true
    name: trafeik

  external:

  internal:
    internal: true

  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.11.0/24


volumes:
  pihole-config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/pihole-config

  pihole-dnsmasq:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/pihole-dnsmasq

  sonarr-config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/sonarr-config

  radarr-config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/radarr-config

  jackett-config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/jackett-config

  qbittorrent-config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/qbittorrent-config

  plex-config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/plex-config

  plex-transcode:

  media-center:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=192.168.11.111,rw'
      device: ':/mnt/store/media_center'

  media:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=192.168.11.111,rw'
      device: ':/mnt/store/media_center/media'

  torrents:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=192.168.11.111,rw'
      device: ':/mnt/store/media_center/torrents'
