---
- name: Create build directory
  file:
    path: "{{ build_dir }}"
    state: directory

- name: Copy source files to build directory
  synchronize:
    src: ../src/
    dest: "{{ build_dir }}"
    recursive: yes
    delete: yes

- name: Build docker-compose.yml
  template:
    src: ./templates/docker-compose.yml.j2
    dest: "{{ build_dir }}/docker-compose.yml"
