#!/bin/bash

# config according to instructions at
# https://pve.proxmox.com/wiki/Cloud-Init_Support

{ error=$(qm set $1 --ide2 local-zfs:cloudinit 2>&1 1>&$out); } {out}>&1

set -e
if [ $? -eq 0 ]; then
  if [[ $error == *"Configuration file"*"does not exist"* ]]; then
      echo "vm with id $1 does not exist" 1>&2
      exit 64
  elif [[ $error == *"dataset already exists"* ]]; then
      echo "cloud-init drive already created"
  else
      echo "unexpected error: $error" 1>&2
      exit 1
  fi
else
  qm set $1 --boot c --bootdisk scsi0
  qm set $1 --serial0 socket --vga serial0
fi
