version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   networks:
  #     public:
  #       ipv4_address: 192.168.11.3
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #     - "80:80/tcp"
  #     - "443:443/tcp"
  #   environment:
  #     TZ: 'America/Los_Angeles'
  #     WEBPASSWORD: 'this-is-a-Password!'
  #   # Volumes store your data between container upgrades
  #   volumes:
  #      - ./pihole-config:/etc/pihole/
  #      - ./pihole-dnsmasq:/etc/dnsmasq.d/
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1
  #   # Recommended but not required (DHCP needs NET_ADMIN)
  #   #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped

  # duckdns:
  #   # container_name: duckdns
  #   image: linuxserver/duckdns
  #   environment:
  #     # PUID: 2000 # optional
  #     # PGID: 2000 # optional
  #     TZ: 'America/Los_Angeles'
  #     SUBDOMAINS: 'michaelbick'
  #     TOKEN: '50b63b4c-0fc0-43a2-a10f-9dea16c77dd5'
  #     LOG_FILE: 'false' # optional
  #   volumes:
  #     - ./duckdns-config:/config #optional
  #   restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=America/Los_Angeles
      # - UMASK_SET=022 # causes permissions issues with NFS
    volumes:
      - ./radarr-config:/config
      - movies:/movies
      - downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=Europe/London
      # - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent-config:/config
      - downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

networks:
  public:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.11.0/24

volumes:
  radarr-config:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=192.168.11.111,rw'
      device: ':/mnt/store/docker/configs/radarr'

  movies:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=192.168.11.111,rw'
      device: ':/mnt/store/media/movies'

  downloads:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=192.168.11.111,rw'
      device: ':/mnt/store/downloads'
