---
    - name: Create build directory
      file:
        path: "{{ build_dir }}"
        state: directory
      tags:
        - mbick-docker

    - name: Build docker-compose.yml
      template:
        src: ../templates/docker-compose.yml.j2
        dest: "{{ build_dir }}/docker-compose.yml"
      tags:
        - mbick-docker
