version: "3.7"
services:
  packer:
    build:
      context: .
      args:
        TEMPLATE_DIR: "${TEMPLATE_DIR}"
    environment:
      - BUILD_DIR
      - PACKER_LOG
    volumes:
      - "./templates/:${TEMPLATE_DIR}"
      - "./build/:${BUILD_DIR}"
    privileged: true
