version: "3.7"
services:
  packer:
    image: hashicorp/packer:light
    environment:
      - PACKER_LOG
    volumes:
      - "./templates/:${TEMPLATE_DIR}"
    working_dir: "${TEMPLATE_DIR}"

  packer-master:
    build: ./packer-master
    environment:
      - PROVISION_DIR
      - PACKER_LOG
    volumes:
      - "./templates/:${TEMPLATE_DIR}"
      - "../provisioning/:${PROVISION_DIR}"
    working_dir: "${TEMPLATE_DIR}"

  packer-qemu:
    build:
      context: .
      args:
        TEMPLATE_DIR: "${TEMPLATE_DIR}"
    environment:
      - BUILD_DIR
      - PACKER_LOG
    volumes:
      - "./templates/:${TEMPLATE_DIR}"
      - "./build/:${BUILD_DIR}"
    privileged: true
