---
# mbick.hashicorp_vault
hashicorp_vault_version: 1.3.1
# hashicorp_vault_domain: vault.example.com # will be used when I setup TLS certification

# geerlingguy.docker
docker_install_compose: false

# TODO: replace this with an actual compose file
ct_users:
  - name: media
    id: 10000
containers:
  - name: transmission
    image: linuxserver/transmission:145
    user: media
    volumes:
      - source: transmission-config
        dest: /config
      - source: downloads
        dest: /downloads
      - source: transmission-watch
        dest: /watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  - name: radarr
    image: linuxserver/radarr:134
    user: media
    volumes:
      - source: radarr-config
        dest: /config
      - source: downloads
        dest: /downloads
      - source: movies
        dest: /movies
    ports:
      - 7878:7878

mount_dir: /mnt/volumes
rclone_dir: gt-onedrive:/mbick-server
volumes:
  - name: movies
    type: rclone
    owner: media
    encrypt: yes
  # - name: tv-shows
  #   type: rclone
  #   owner: media
  #   encrypt: yes
  - name: downloads
    type: mount-dir
    owner: media
  - name: transmission-watch
    type: local
    owner: media
  - name: transmission-config
    type: bind
    source: "{{ docker_dir }}/transmission/config"
    owner: media
  - name: radarr-config
    type: local
    source: "{{ docker_dir }}/radarr/config"
    owner: media
  # - name: sonarr-config
  #   type: bind
  #   owner: media

rclone_mount_options: --allow-non-empty
