version: "3.8"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    networks:
      - traefik
    ports:
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8090:8080
    volumes:
      # For Traefik's automated config to work, the docker socket needs to be
      # mounted. There are some security implications to this.
      # See https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
      # and https://docs.traefik.io/providers/docker/#docker-api-access
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--providers.docker.defaultRule=Host(`{{ normalize .Name }}.michaelbick.duckdns.org`)"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.traefik.rule=Host(`traefik.michaelbick.duckdns.org`)'
      - 'traefik.http.routers.traefik.service=api@internal'
    restart: unless-stopped

  wg-access-server:
    build:
      context: ./wg-access-server
      args:
        WG_ACCESS_SERVER_TAG: latest
        VAULT_TAG: 1.4.3
    # image: place1/wg-access-server
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
    volumes:
      - "wg-access-server-config:/data"
    environment:
      UPSTREAM_DNS: 192.168.11.3
      VAULT_ADDR: "${VAULT_ADDR}"
      VAULT_TOKEN: "${VAULT_TOKEN}"
    networks:
      - traefik
    ports:
      - "8000:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.michaelbick.duckdns.org`)"
      - "traefik.http.services.wireguard.loadbalancer.server.port=8000"
    restart: unless-stopped


networks:
  traefik:
    name: traefik

  # macvlan:
  #   name: macvlan
  #   driver: macvlan
  #   driver_opts:
  #     parent: eth0
  #   ipam:
  #     config:
  #       - subnet: 192.168.11.0/24


volumes:
  wg-access-server-config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker_volumes/wg-access-server-config
