#!/bin/bash

if [ ${#@} == 0 ] | [ $1 == "-h" ]; then
    echo "Usage: `basename $0` [file] [variable_name]"
else
    PATTERN="$2"'=.*'
    VAR=$(grep -e $PATTERN $1 | cut -d '=' -f2)
    echo $VAR
fi
