---
- hosts: all
  become: yes
  roles:
    - { role: "nickjj.docker", tags: ["docker"] }

  tasks:
    - name: Create groups
      group:
        gid: "{{ item.id }}"
        name: "{{ item.name }}"
        state: present
      loop: "{{ users }}"

    - name: Create users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        state: present
        uid: "{{ item.id }}"
      loop: "{{ users }}"

    - name: Create mountpoints for containers
      file:
        path: "/mnt/disks/{{ item.name }}"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        state: directory
        mode: 0775
      loop: "{{ users }}"
      when: item.host_mount is defined and item.host_mount

    # - name: Build and run docker-compose
    #   shell: ls && docker-compose up -d
