---
- hosts: vms
  tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Install cloud-init
      apt:
        name: cloud-init
        state: present

    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
