---
- hosts: all
  become: yes
  pre_tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present
  roles:
    - { role: "nickjj.docker", tags: ["docker"] }

  tasks:
    - name: Create groups
      group:
        name: "{{ item.name }}"
        gid: "{{ item.id }}"
        state: present
      loop: "{{ ct_users }}"

    - name: Create users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.id }}"
        groups: "[ '{{ item.name }}' ] + {{ item.groups | default([]) }}"
        create_home: no
        state: present
      loop: "{{ ct_users }}"

    - name: Create mountpoints for containers
      file:
        path: "/mnt/disks/{{ item.name }}"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        state: directory
        mode: 0775
      loop: "{{ ct_users }}"
      when: item.host_mount is defined

    - name: Add container users to vagrant group for development
      user:
        name: "{{ item.name }}"
        groups:
          - vagrant
        append: yes
      loop: "{{ ct_users }}"

    # - name: Build and run docker-compose
    #   shell: ls && docker-compose up -d
