#!/usr/bin/env bash

SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"

eval $(dhall-to-bash --declare VAULT_ADDRESS <<< "let packages = ${SRC_DIR}/packages.dhall in packages.mbick-server.vault.sign-ssh.address")

# TODO: implement host key checking
SSH_CMD="vault write \
    -address=$VAULT_ADDRESS \
    -field=signed_key \
    public_key=@$HOME/.ssh/id_rsa.pub \
    > $HOME/.ssh/id_rsa-cert.pub
echo $SSH_CMD
eval $SSH_CMD