---
ct_users:
  - name: rclone
    id: 10100
  - name: movies
    id: 10110
    groups:
      - rclone
    mount_type: rclone
  - name: tv-shows
    id: 10111
    groups:
      - rclone
    mount_type: rclone
  - name: downloads
    id: 10200
    mount_type: rclone
  - name: transmission
    id: 10210
    groups:
      - downloads
    mount_type: rclone
  - name: radarr
    id: 10220
    groups:
      - downloads
      - movies
    mount_type: rclone
  - name: sonarr
    id: 10221
    groups:
      - downloads
      - tv-shows
    mount_type: rclone
  - name: plex
    id: 10300
    groups:
      - movies
      - tv-shows

# Pin Docker version 18.06 from the stable channel.
# docker_version: "18.06"

# Allow the admin and zerocool users to access Docker without needing root access.
docker_users: ["vagrant"]

# A couple of examples of authenticating to a Docker registry.
# docker_registries:
#   # Authenticate to the Docker Hub, and allow the "admin" system user acces to it:
#   - username: "mbick"
#     password: ""
#     email: "mafbick@gmail.com"
#     system_user: "{{ docker_users | first }}"
#   # Authenticate to some other private registry and allow "zerocool":
#   - registry_url: "https://your-registry.com"
#     username: "some_other_username"
#     password: "some_other_password"
#     system_user: "zerocool"
#   # Disable logging in to some old registry you don't use anymore:
#   - registry_url: "https://old-registry.com"
#     username: "some_old_username"
#     password: "some_old_password"
#     state: "absent"
