---
timezone: Atlanta/America

docker_compose_file_version: 3.7

root_dir: /vagrant
src_dir: /vagrant/src
build_dir: /vagrant/build

ct_users:
  - name: media
    id: 10000
containers:
  - name: transmission
    image: linuxserver/transmission:145
    user: media
    volumes:
      - source: transmission-config
        dest: /config
      - source: downloads
        dest: /downloads
      - source: transmission-watch
        dest: /watch

mount_dir: /mnt/volumes
rclone_dir: gt-onedrive:/mbick-server
volumes:
  # - name: movies
  #   type: rclone
  #   owner: media
  #   encrypt: yes
  # - name: tv-shows
  #   type: rclone
  #   owner: media
  #   encrypt: yes
  - name: downloads
    type: rclone
    owner: media
  - name: transmission-watch
    type: rclone
    owner: media
  - name: transmission-config
    type: rclone
    owner: media
  # - name: radarr
  #   type: rclone
  #   owner: media
  # - name: sonarr
  #   type: rclone
  #   owner: media

rclone_mount_options: --allow-non-empty

# Pin Docker version 18.06 from the stable channel.
# docker_version: "18.06"

# Allow the admin and zerocool users to access Docker without needing root access.
docker_users: ["vagrant"]

# A couple of examples of authenticating to a Docker registry.
# docker_registries:
#   # Authenticate to the Docker Hub, and allow the "admin" system user acces to it:
#   - username: "mbick"
#     password: ""
#     email: "mafbick@gmail.com"
#     system_user: "{{ docker_users | first }}"
#   # Authenticate to some other private registry and allow "zerocool":
#   - registry_url: "https://your-registry.com"
#     username: "some_other_username"
#     password: "some_other_password"
#     system_user: "zerocool"
#   # Disable logging in to some old registry you don't use anymore:
#   - registry_url: "https://old-registry.com"
#     username: "some_old_username"
#     password: "some_old_password"
#     state: "absent"
