version: "3.7"
services:
  packer:
    image: hashicorp/packer:light
    networks:
      - macvlan
    environment:
      - PROVISION_DIR
      - PACKER_LOG
    volumes:
      - "./templates/:${TEMPLATE_DIR}"
      - "../provisioning/:${PROVISION_DIR}"
    working_dir: "${TEMPLATE_DIR}"

  packer-master:
    build: .
    networks:
      - macvlan
    environment:
      - PROVISION_DIR
      - PACKER_LOG
    volumes:
      - "./templates/:${TEMPLATE_DIR}"
      - "../provisioning/:${PROVISION_DIR}"
    # working_dir: "${TEMPLATE_DIR}"
    working_dir: "${TEMPLATE_DIR}/ubuntu"

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: en0.30
    ipam:
      config:
        - subnet: 192.168.11.0/24
        # - gateway: 192.168.11.1
